apiVersion: v1
kind: Pod
metadata:
  name: parking-lot-app
  labels:
    app: parking-lot-app
spec:
  containers:
    - name: parking-lot-app
      image: parking_test:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 9000
      envFrom:
        - configMapRef:
            name: example-config
